import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { SidebarModule } from 'primeng/sidebar';
import { TooltipModule } from 'primeng/tooltip';
import { ButtonModule } from 'primeng/button';
import { LazyLoadImageModule } from 'ng-lazyload-image';
import { SidebarMenuComponent } from './sidebar-menu.component';
import { CapitalizeFirstPipe } from 'src/app/pipes/capitalize.pipe';
import {
  LucideAngularModule,
  LogOut,
  Calculator,
  LayoutDashboard,
  BookSearch,
  Settings,
  Blocks,
  ReceiptIndianRupee,
  FileChartPie,
  Files,
  Landmark,
  ShieldUser,
  LogIn,
  FolderCog,
  PhoneCall,
  MessagesSquare,
  ChartNoAxesCombined,
  Users,
  FolderOpen,
  Gauge,
  ShieldCheck,
  Wallet,
  XCircle,
  BadgeCheck,
  BadgeIndianRupee,
  BadgeX,
  IdCardLanyard,
  UserCheck,
  HandCoins,
  UserX,
  TrendingUp,
  CalendarDays ,
  Sun,
  WifiCog,
  BanknoteArrowUp
} from 'lucide-angular';
@NgModule({
  declarations: [SidebarMenuComponent],
  imports: [
    CommonModule,
    RouterModule,
    SidebarModule,
    TooltipModule,
    ButtonModule,
    LazyLoadImageModule,
    CapitalizeFirstPipe,
    LucideAngularModule.pick({
      Calculator,
      LogOut,
      ChartNoAxesCombined,
      BookSearch,
      Settings,
      Blocks,
      ReceiptIndianRupee,
      FileChartPie,
      Landmark,
      ShieldUser,
      Files,
      LogIn,
      FolderCog,
      PhoneCall,
      MessagesSquare,
      LayoutDashboard,
      Users,
      FolderOpen,
      Gauge,
      ShieldCheck,
      Wallet,
      XCircle,
      BadgeCheck,
      BadgeIndianRupee,
      BadgeX,
      IdCardLanyard,
      UserCheck,
      HandCoins ,
      UserX ,
      TrendingUp ,
      CalendarDays,
      Sun,
      WifiCog,
      BanknoteArrowUp
    }),
  ],
  exports: [SidebarMenuComponent],
})
export class SidebarMenuModule {}
